<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.5.4 setup script
 * Date: Fri, 29 Jan 2016 12:34:04 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: sourcelair [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'sourcelair';
$cfg['Servers'][$i]['host'] = 'mysql';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = '';

/* End of servers configuration */
$cfg['blowfish_secret'] = '56ab5b9bda6305.64858666';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>